In [107]:
# Завдання:1
# Створіть одновимірний масив з елементами від 5 до 15. Змініть форму цього масиву на 2x5. 
# Отримайте всі елементи, які більші за 10. Порахуйте кількість елементів у вашому масиві, які діляться на 3 без залишку.

In [108]:
import numpy as np

In [109]:
arr = np.array([5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
print(arr)

[ 5  6  7  8  9 10 11 12 13 14]


In [110]:
print(arr.reshape(2, 5))

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [111]:
arr[arr > 10]

array([11, 12, 13, 14])

In [112]:
arr[arr % 3 == 0]

array([ 6,  9, 12])

In [113]:
# Завдання:2
# Створіть масив 3x3 з нулів, а потім замініть центральний елемент на 1. Відніміть 2 від усіх елементів.

In [114]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [115]:
arr[1, 1] = 1
print(arr)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


In [116]:
arr = arr - 2
print(arr)

[[-2. -2. -2.]
 [-2. -1. -2.]
 [-2. -2. -2.]]


In [1]:
# Завдання: 3
# Створіть два масиви різних форм і спробуйте виконати арифметичні операції над ними. Поясніть результат.

In [118]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

result_add = arr1 + arr2
print(result_add)

[[11 22 33]
 [14 25 36]]


In [119]:
result_multiply = arr1 * arr2
print(result_multiply)

[[ 10  40  90]
 [ 40 100 180]]
